# Generated by Django 4.2 on 2023-05-04 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plyty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.TextField()),
                ('tytul', models.TextField()),
                ('ilosc_utworow', models.IntegerField()),
                ('rok_wydania', models.IntegerField()),
                ('gatunek', models.TextField()),
                ('opis', models.TextField()),
                ('zdjecie', models.TextField()),
                ('cena', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ilosc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pracownicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon_sluzbowy', models.TextField()),
                ('czy_kierownik', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wykonawca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudonim', models.TextField()),
                ('czy_zespol', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_uzytkownika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wykonawcy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_plyty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.plyty')),
                ('id_wykonawcy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.wykonawca')),
            ],
        ),
        migrations.CreateModel(
            name='SzczegolyZamowienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.IntegerField()),
                ('id_plyty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.plyty')),
                ('id_zamowienia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.zamowienia')),
            ],
        ),
        migrations.CreateModel(
            name='Raporty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od', models.DateField()),
                ('do', models.DateField()),
                ('ilosc', models.IntegerField()),
                ('suma', models.DecimalField(decimal_places=2, max_digits=10)),
                ('czy_automatyczny', models.BooleanField()),
                ('id_pracownika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.pracownicy')),
            ],
        ),
        migrations.CreateModel(
            name='Klienci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon_prywatny', models.TextField()),
                ('adres1', models.TextField()),
                ('adres2', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
