# Generated by Django 4.2 on 2023-05-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plyty',
            name='zdjecie',
        ),
        migrations.AlterField(
            model_name='plyty',
            name='rodzaj',
            field=models.TextField(choices=[('cd', 'Płyta CD'), ('winyl', 'Winyl'), ('kaseta', 'Kaseta magnetofonowa')], default='cd'),
        ),
    ]
