# Generated by Django 4.2 on 2023-05-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_plyty_zdjecie_alter_plyty_rodzaj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wykonawcy',
            name='id_plyty',
        ),
        migrations.RemoveField(
            model_name='wykonawcy',
            name='id_wykonawcy',
        ),
        migrations.AddField(
            model_name='plyty',
            name='wykonawca',
            field=models.TextField(default='wykonawca'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Wykonawca',
        ),
        migrations.DeleteModel(
            name='Wykonawcy',
        ),
    ]
