# Generated by Django 4.2 on 2023-05-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_wykonawcy_id_plyty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plyty',
            name='rodzaj',
            field=models.TextField(choices=[('CD', 'Płyta CD'), ('winyl', 'Winyl'), ('kaseta', 'Kaseta magnetofonowa')], default='CD'),
        ),
    ]
