# Generated by Django 4.2 on 2023-05-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_plyty_rodzaj'),
    ]

    operations = [
        migrations.AddField(
            model_name='plyty',
            name='quantity',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
