# Generated by Django 4.2 on 2023-05-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_plyty_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiadomosci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.TextField()),
                ('email', models.TextField()),
                ('temat', models.TextField()),
                ('tresc', models.TextField()),
            ],
        ),
    ]
