# Generated by Django 4.2 on 2023-06-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_wiadomosci'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plyty',
            options={'verbose_name': 'płyta', 'verbose_name_plural': 'płyty'},
        ),
        migrations.AlterModelOptions(
            name='wiadomosci',
            options={'verbose_name': 'wiadomość', 'verbose_name_plural': 'wiadomości'},
        ),
        migrations.AddField(
            model_name='plyty',
            name='okladka',
            field=models.FileField(upload_to='static/shop/img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plyty',
            name='cena',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='plyty',
            name='gatunek',
            field=models.CharField(max_length=64, verbose_name='Gatunek'),
        ),
        migrations.AlterField(
            model_name='plyty',
            name='ilosc',
            field=models.IntegerField(verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='plyty',
            name='ilosc_utworow',
            field=models.IntegerField(verbose_name='Ilość utworów'),
        ),
        migrations.AlterField(
            model_name='plyty',
            name='opis',
            field=models.TextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='plyty',
            name='rodzaj',
            field=models.TextField(choices=[('CD', 'Płyta CD'), ('winyl', 'Winyl'), ('kaseta', 'Kaseta magnetofonowa')], default='CD', verbose_name='Rodzaj'),
        ),
        migrations.AlterField(
            model_name='plyty',
            name='rok_wydania',
            field=models.IntegerField(verbose_name='Rok wydania'),
        ),
        migrations.AlterField(
            model_name='plyty',
            name='tytul',
            field=models.CharField(max_length=64, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='plyty',
            name='wykonawca',
            field=models.CharField(max_length=64, verbose_name='Wykonawca'),
        ),
        migrations.AlterField(
            model_name='wiadomosci',
            name='email',
            field=models.CharField(max_length=64, verbose_name='Adres e-mail'),
        ),
        migrations.AlterField(
            model_name='wiadomosci',
            name='imie',
            field=models.CharField(max_length=64, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='wiadomosci',
            name='temat',
            field=models.CharField(max_length=64, verbose_name='Temat'),
        ),
        migrations.AlterField(
            model_name='wiadomosci',
            name='tresc',
            field=models.TextField(verbose_name='Treść'),
        ),
    ]
