# Generated by Django 4.2 on 2023-06-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_plyty_options_alter_wiadomosci_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plyty',
            name='okladka',
        ),
    ]
