# Generated by Django 4.2 on 2023-06-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_plyty_okladka'),
    ]

    operations = [
        migrations.AddField(
            model_name='plyty',
            name='okladka',
            field=models.FileField(default='product_0.jpg', upload_to='static/shop/img'),
        ),
    ]
