# Generated by Django 4.2 on 2023-06-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_plyty_okladka'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plyty',
            options={'ordering': ['id'], 'verbose_name': 'płyta', 'verbose_name_plural': 'płyty'},
        ),
        migrations.AlterField(
            model_name='plyty',
            name='okladka',
            field=models.FileField(upload_to='static/shop/img'),
        ),
    ]
