# Generated by Django 4.2 on 2023-06-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_plyty_options_alter_plyty_okladka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plyty',
            name='okladka',
            field=models.FileField(),
        ),
    ]
