# Generated by Django 4.2 on 2023-06-15 08:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_plyty_okladka'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raporty',
            options={'verbose_name': 'raport', 'verbose_name_plural': 'raporty'},
        ),
        migrations.AlterModelOptions(
            name='szczegolyzamowienia',
            options={'verbose_name': 'szczegóły zamówienia', 'verbose_name_plural': 'szczegóły zamówienia'},
        ),
        migrations.AlterModelOptions(
            name='zamowienia',
            options={'verbose_name': 'zamówienie', 'verbose_name_plural': 'zamówienia'},
        ),
        migrations.AddField(
            model_name='szczegolyzamowienia',
            name='cena',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Cena'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zamowienia',
            name='data_zlozenia',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plyty',
            name='okladka',
            field=models.FileField(upload_to='', verbose_name='Okładka'),
        ),
        migrations.AlterField(
            model_name='szczegolyzamowienia',
            name='id_plyty',
            field=models.ForeignKey(db_column='ID płyty', on_delete=django.db.models.deletion.CASCADE, to='shop.plyty'),
        ),
        migrations.AlterField(
            model_name='szczegolyzamowienia',
            name='id_zamowienia',
            field=models.ForeignKey(db_column='ID zamówienia', on_delete=django.db.models.deletion.CASCADE, to='shop.zamowienia'),
        ),
        migrations.AlterField(
            model_name='szczegolyzamowienia',
            name='ilosc',
            field=models.IntegerField(verbose_name='Ilość'),
        ),
    ]
