# Generated by Django 4.2 on 2023-06-15 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_raporty_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='szczegolyzamowienia',
            old_name='id_plyty',
            new_name='plyta',
        ),
        migrations.RenameField(
            model_name='szczegolyzamowienia',
            old_name='id_zamowienia',
            new_name='zamowienie',
        ),
    ]
