# Generated by Django 4.2 on 2023-06-16 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_szczegolyzamowienia_options_plyty_sprzedano_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pracownicy',
            name='user',
        ),
        migrations.RemoveField(
            model_name='raporty',
            name='id_pracownika',
        ),
        migrations.DeleteModel(
            name='Klienci',
        ),
        migrations.DeleteModel(
            name='Pracownicy',
        ),
        migrations.DeleteModel(
            name='Raporty',
        ),
    ]
